### ISSUE TITLE
Add: Template for a Online Form

### ISSUE THREAD

**Issue by theprinceraj** [vaishnavi-3969/Web-Componentify#11]
A template for a generic online web form that has fields for most commonly needed/asked information in online web forms like name, email, phone etc.

**Comment by theprinceraj** [comment]
I would love to contribute to this cause and help in the growth of this public repository. Please assign me this issue. @vaishnavi-3969 @Hansika002

**Comment by vaishnavi-3969** [comment]
Thanks for raising this issue ❤️. It is assigned to you @theprinceraj you can start working on it 😄

**Comment by theprinceraj** [comment]
I have made the necessary PR for this issue. Make sure to label the PR with hacktoberfest-accepted after reviewing it.
#29 And please inform me if I have made a mistake with how PRs are usually done since it is my first time.

**Comment by theprinceraj** [comment]
@vaishnavi-3969 Could you please check my PR please?
