### ISSUE TITLE
Customized Bottom navigation Bar

### ISSUE THREAD

**Issue by Pavan-Sai-padavala** [vaishnavi-3969/Web-Componentify#28]
In Single Page Applications, to navigate across the pages , a customized bottom navigation bar is helpful in creating nice user experience.
![image](https://github.com/vaishnavi-3969/Web-Componentify/assets/72682254/629fff8b-9f2d-440b-b340-78277e4c2812)

**Comment by vaishnavi-3969** [comment]
Thanks for raising the issue @Pavan-Sai-padavala you have been assigned this issue you can start working on this :)
