### ISSUE TITLE
Footer styling needs correction in home page.

### ISSUE THREAD

**Issue by farhanalws4u** [vaishnavi-3969/Web-Componentify#37]
The styling of the footer on the home page is not optimal. it needs some responsive CSS and also alignment. 

I want to work on this issue. Please assign me and mark it as hacktoberfest.

thank you.

**Comment by vaishnavi-3969** [comment]
Hey @farhanalws4u! Thank you for raising an issue 💗 You have been assigned this issue you can start working on this👍🏻😄
