### ISSUE TITLE
Feature: Add Animation Effects for Accordion Open/Close

### ISSUE THREAD

**Issue by Jenish-Dhanani** [vaishnavi-3969/Web-Componentify#40]
Description: I would like to propose adding animation effects to the accordion component in order to provide a more visually appealing user experience. Currently, the accordion opens and closes abruptly, which can be jarring for users.

I suggest implementing a smooth animation transition when the accordion is opened or closed. This could involve using CSS transitions or JavaScript animations to gradually expand or collapse the accordion content.

Benefits:

Improved User Experience: Animation effects will make the accordion open and close more smoothly, providing a more polished and intuitive user experience.
Visual Feedback: Animations will provide visual feedback to users, clearly indicating the state change of the accordion.
Modern and Engaging: Adding animation effects will make the accordion feel more modern and engaging, enhancing the overall aesthetics of the application.
Possible Implementation:

Utilize CSS transitions to smoothly animate the expansion and collapse of the accordion content.
I am willing to contribute to this feature implementation and would appreciate any guidance or feedback from the maintainers on the best approach to take. Thank you!

**Comment by vaishnavi-3969** [comment]
Hey thanks for raising the issue you have been assigned this @Jenish-Dhanani you can start working on it 😄

**Comment by Jenish-Dhanani** [comment]
Result:
Before:

https://github.com/vaishnavi-3969/Web-Componentify/assets/99007146/900963ed-38b8-4f39-8aae-98fc0f1ec3ba

After:

https://github.com/vaishnavi-3969/Web-Componentify/assets/99007146/192ce229-36f2-43c2-beb2-74bb2b72451d
