### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by Akshayp02** [vaishnavi-3969/Web-Componentify#41]
To add Dependabot to a project, create a `dependabot.yml` file in project root. Configure it to check for updates in  project's dependencies, and set up notifications for automated pull requests. Dependabot will then help  keep  dependencies up-to-date, enhancing project stability and security.

**Comment by vaishnavi-3969** [comment]
Hey thanks for raising the issue you have been assigned this @Akshayp02 you can start working on it 😄
