### ISSUE TITLE
Modal and website layout not responsive getting scrollbar in bottomch

### ISSUE THREAD

**Issue by mahendrameghwal** [vaishnavi-3969/Web-Componentify#50]
https://webcomponentify.design/Modal this URL when i clicked on the click on the instrucation button the modal size is oversized and it's impacting user exprience 

here is the issue : https://i.imgur.com/ozQRNPZ.png

i will  work on this  issue

**Comment by mahendrameghwal** [comment]
and please add to label of hackroberfest

**Comment by vaishnavi-3969** [comment]
Hey @mahendrameghwal thanks for raising the issue :sparkle:
You can start working on it I have assigned it to you

**Comment by mahendrameghwal** [comment]
ok
