### ISSUE TITLE
Add: An online web form using Google Firebase Realtime Database 

### ISSUE THREAD

**Issue by theprinceraj** [vaishnavi-3969/Web-Componentify#60]
Template for an online web form using Google's Firebase Realtime Database

**Comment by theprinceraj** [comment]
@vaishnavi-3969 I would like to work on this issue. Please assign me the same! 🙌

**Comment by vaishnavi-3969** [comment]
hey @theprinceraj thanks for raising the issue 😄

**Comment by theprinceraj** [comment]
#64 
Here is the PR

**Comment by theprinceraj** [comment]
@vaishnavi-3969 Can you please merge it if there are no issues?
