### ISSUE TITLE
Implement Footer Component

### ISSUE THREAD

**Issue by suryanshsingh2001** [vaishnavi-3969/Web-Componentify#9]
#### Description

**Summary:**

Create and implement a Footer component for the website to enhance user experience and provide social media links.

**Details:**

We need to add a footer component to the website. The footer should include social media icons with captivating hover animations and links to our social media profiles.

**Requirements:**

- [ ] Create a new `Footer.jsx` component.
- [ ] Style the footer using Tailwind CSS.
- [ ] Add social media icons using FontAwesome icons.
- [ ] Implement hover animations for the icons.
- [ ] Add links to social media profiles (e.g., Twitter, Facebook, Instagram, LinkedIn).

**Additional Information:**

- Please refer to the design guidelines for the styling and layout of the footer.
- Make sure the footer is responsive and works well on different screen sizes.
- Test the hover animations to ensure they provide a delightful user experience.

**Expected Output:**

A fully functional and styled footer component that includes social media icons with hover animations and links to our social media profiles.

**Package Dependencies**

We will be using FontAwesome icons for this task. To get started, please install FontAwesome by adding it to the `dependencies` in your `package.json` file:

```bash
npm install --save @fortawesome/fontawesome-free
```

#### Hacktoberfest:
 To make this issue eligible for Hacktoberfest, please label it as:
- `hacktoberfest`
- `hacktoberfest-accepted`

**Comment by suryanshsingh2001** [comment]
@vaishnavi-3969 Please assign this issue to me.

**Comment by vaishnavi-3969** [comment]
Thanks for raising this issue ❤️. It is assigned to you @suryanshsingh2001 you can start working on it 😄

**Comment by suryanshsingh2001** [comment]
@vaishnavi-3969  I have made the necessary PR for this issue. Make sure to label the PR with hacktoberfest-accepted after reviewing it. 

https://github.com/vaishnavi-3969/Web-Componentify/pull/20
